MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  NUM_CLASSES: 7
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.02
  GAMMA: 0.1
  MAX_ITER: 30000
  STEPS: [0, 10000, 20000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  # FREEZE_AT: 0
  DATASETS: ('nucoco_train',)
  SCALES: (900,)
  MAX_SIZE: 1600
  IMS_PER_BATCH: 4
  BATCH_SIZE_PER_IM: 512
  SNAPSHOT_ITERS: 5000
TEST:
  DATASETS: ('nucoco_val',)
  PROPOSAL_LIMIT: 2000
  SCALE: 900
  MAX_SIZE: 1600
  NMS: 0.5
